# Generated by Django 5.1.3 on 2025-06-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0160_alter_products_exclude_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beposoft_app.family'),
        ),
    ]
