# Generated by Django 5.1.3 on 2025-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0161_customers_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Invoice Created', 'Invoice Created'), ('Invoice Approved', 'Invoice Approved'), ('Waiting For Confirmation', 'Waiting For Confirmation'), ('To Print', 'To Print'), ('Invoice Rejected', 'Invoice Rejected'), ('Order Request by Warehouse', 'Order Request by Warehouse'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Rejected', 'Rejected'), ('Return', 'Return'), ('Packing under progress', 'Packing under progress'), ('Packed', 'Packed'), ('Ready to ship', 'Ready to ship')], default='pending', max_length=100),
        ),
    ]
