# Generated by Django 5.1.3 on 2025-09-10 08:52

import beposoft_app.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0162_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, default='', max_length=50)),
                ('country_name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'CountryCode',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ProductCategoryModel',
            },
        ),
        migrations.AddField(
            model_name='beposoftcart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grvmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.products'),
        ),
        migrations.AddField(
            model_name='grvmodel',
            name='rack_details',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='grvmodel',
            name='selected_racks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='accounts_note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to='beposoft_app.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_orders', to='beposoft_app.user'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rack_details',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='damaged_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='duty_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='partially_damaged_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rack_details',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='warehousedata',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[beposoft_app.validators.validate_gst]),
        ),
        migrations.AlterField(
            model_name='grvmodel',
            name='remark',
            field=models.CharField(choices=[('return', 'Return'), ('refund', 'Refund'), ('exchange', 'Exchange')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grvmodel',
            name='returnreason',
            field=models.CharField(choices=[('damaged', 'damaged'), ('partially_damaged', 'partially_damaged'), ('usable', 'usable')], default='usable', max_length=200),
        ),
        migrations.AlterField(
            model_name='grvmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('Waiting For Approval', 'Waiting For Approval')], default='Waiting For Approval', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='beposoft_app.shipping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehousedata',
            name='box',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousedata',
            name='breadth',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='warehousedata',
            name='length',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='warehousedata',
            name='packed_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user'),
        ),
        migrations.AlterField(
            model_name='warehousedata',
            name='weight',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
        migrations.CreateModel(
            name='AdvanceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt', models.CharField(editable=False, max_length=15, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionID', models.CharField(max_length=50)),
                ('received_at', models.DateField()),
                ('remark', models.TextField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_receipts', to='beposoft_app.bank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_receipts', to='beposoft_app.customers')),
            ],
            options={
                'db_table': 'advance_receipts',
            },
        ),
        migrations.CreateModel(
            name='BankReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt', models.CharField(editable=False, max_length=15, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionID', models.CharField(max_length=50)),
                ('received_at', models.DateField()),
                ('remark', models.TextField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipts', to='beposoft_app.bank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
            ],
            options={
                'db_table': 'bank_receipts',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('active_calls', models.PositiveIntegerField(help_text='Number of active calls')),
                ('phone_number', models.CharField(max_length=15)),
                ('call_duration_seconds', models.PositiveIntegerField()),
                ('call_date', models.DateField()),
                ('start_time', models.DateTimeField(help_text='Start time of the call')),
                ('end_time', models.DateTimeField(help_text='End time of the call')),
                ('bill_count', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('family_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.family')),
            ],
            options={
                'db_table': 'calllog',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beposoft_app.countrycode'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beposoft_app.countrycode'),
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beposoft_app.customertype'),
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('transactionID', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
                ('receiver_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='beposoft_app.bank')),
                ('sender_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='beposoft_app.bank')),
            ],
            options={
                'db_table': 'internal_transfer',
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_images', to='beposoft_app.order')),
            ],
            options={
                'db_table': 'order_images',
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_images', to='beposoft_app.order')),
            ],
            options={
                'db_table': 'order_payment_images',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='beposoft_app.productcategorymodel'),
        ),
        migrations.CreateModel(
            name='ProductRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.PositiveIntegerField()),
                ('rack_name', models.CharField(blank=True, max_length=50)),
                ('column_name', models.CharField(blank=True, max_length=50)),
                ('usability', models.CharField(choices=[('usable', 'usable'), ('damaged', 'damaged')], max_length=20)),
                ('rack_stock', models.PositiveIntegerField(default=0)),
                ('locked_stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='beposoft_app.products')),
            ],
            options={
                'unique_together': {('product', 'rack_id', 'column_name', 'usability')},
            },
        ),
        migrations.CreateModel(
            name='RackDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_columns', models.PositiveIntegerField(blank=True, null=True)),
                ('column_names', models.JSONField(blank=True, default=list)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beposoft_app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_data', models.JSONField(blank=True, default=dict, null=True)),
                ('after_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_logs', to='beposoft_app.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_logs', to='beposoft_app.user')),
            ],
            options={
                'db_table': 'data_log',
                'indexes': [models.Index(fields=['created_at'], name='data_log_created_14e1c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItemRackAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_allocations', to='beposoft_app.orderitem')),
                ('product_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.productrack')),
            ],
            options={
                'unique_together': {('order_item', 'product_rack')},
            },
        ),
    ]
