# Generated by Django 5.1.3 on 2025-09-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0163_countrycode_customertype_productcategorymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=20, unique=True)),
                ('order_date', models.CharField(max_length=100)),
                ('shipping_charge', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Received', 'Received')], default='Created', max_length=100)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_billing_address', to='beposoft_app.shipping')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_companies', to='beposoft_app.company')),
                ('manage_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_orders', to='beposoft_app.user')),
                ('receiiver_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_warehouse', to='beposoft_app.warehouse')),
                ('warehouses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_warehouse', to='beposoft_app.warehouse')),
            ],
            options={
                'db_table': 'warehouse_order',
            },
        ),
        migrations.CreateModel(
            name='WarehouseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('rack_details', models.JSONField(blank=True, default=list, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beposoft_app.warehouseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.products')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.productattributevariant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.variantproducts')),
            ],
            options={
                'db_table': 'warehouse_order_item',
            },
        ),
    ]
