# Generated by Django 5.1.3 on 2025-09-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0164_warehouseorder_warehouseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseorder',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Received', 'Received'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Created', max_length=100),
        ),
    ]
