# Generated by Django 5.1.3 on 2025-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0165_alter_warehouseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grvmodel',
            name='cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='COD return amount if applicable', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='grvmodel',
            name='remark',
            field=models.CharField(choices=[('return', 'Return'), ('refund', 'Refund'), ('exchange', 'Exchange'), ('cod_return', 'COD Return')], max_length=20, null=True),
        ),
    ]
