# Generated by Django 5.1.3 on 2025-10-07 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0166_grvmodel_cod_amount_alter_grvmodel_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Productive', 'productive'), ('Inactive', 'inactive')], default='Active', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_report', to='beposoft_app.customers')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.user')),
            ],
            options={
                'db_table': 'callreport',
            },
        ),
    ]
