# Generated by Django 5.1.3 on 2025-10-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0168_contactinfo_alter_callreport_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
