# Generated by Django 5.1.3 on 2025-10-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0169_shipping_alt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='call_audios/'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='call_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
