# Generated by Django 5.1.3 on 2025-11-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0170_callreport_audio_file_callreport_call_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='gst_confirm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
