# Generated by Django 5.1.3 on 2025-11-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0171_customers_gst_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='gst_confirm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questionnaires', to='beposoft_app.user')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='beposoft_app.family')),
            ],
            options={
                'db_table': 'questionnaire',
            },
        ),
    ]
