# Generated by Django 5.1.3 on 2025-11-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0172_alter_customers_gst_confirm_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_answers', to='beposoft_app.user')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_answers', to='beposoft_app.family')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='beposoft_app.questionnaire')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
