# Generated by Django 5.1.3 on 2025-11-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0173_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_answers', to='beposoft_app.customers'),
        ),
    ]
