# Generated by Django 5.1.3 on 2025-11-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0175_contactinfo_district_districts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='districts',
            table='Districts',
        ),
    ]
