# Generated by Django 5.1.3 on 2025-11-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0176_alter_districts_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactdistrict', to='beposoft_app.districts'),
        ),
    ]
