# Generated by Django 5.1.3 on 2025-11-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0177_alter_contactinfo_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_customer', to='beposoft_app.customers')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_staff', to='beposoft_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='StaffOrderUpdateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('note1', models.CharField(blank=True, max_length=100, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beposoft_app.productcategorymodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beposoft_app.stafforderupdate')),
            ],
        ),
    ]
