# Generated by Django 5.1.3 on 2025-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0178_stafforderupdate_stafforderupdateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafforderupdate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
