# Generated by Django 5.1.3 on 2025-11-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0179_stafforderupdate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopify_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
