# Generated by Django 5.1.3 on 2025-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0180_order_shopify_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='call_images/'),
        ),
    ]
