# Generated by Django 5.1.3 on 2025-12-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0181_callreport_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adv_cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_status',
            field=models.CharField(blank=True, choices=[('FULL_COD', 'Full COD'), ('PARTIAL_COD', 'Partial COD')], max_length=20, null=True),
        ),
    ]
