# Generated by Django 5.1.3 on 2025-12-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beposoft_app', '0182_order_adv_cod_amount_order_cod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grvmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grvmodel', to='beposoft_app.order'),
        ),
    ]
