# Generated by Django 5.1.3 on 2025-09-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocart', '0021_expensemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('miscellaneous', 'Miscellaneous'), ('permanent', 'Permanent'), ('emi', 'EMI'), ('cargo', 'Cargo'), ('purchase', 'Purchase')], max_length=100, null=True),
        ),
    ]
